apiVersion: v1
kind: Service

metadata:
  name: student-task-app-service

spec:
  selector:
    app: student-task-app

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

  type: ClusterIP