apiVersion: v1
kind: Service

metadata:
  name: student-task-nginx-service

spec:
  selector:
    app: student-task-nginx

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: LoadBalancer